{
 "title": "Skyhook-NSDI-Experiments",
 "description": "Dashboard showing CPU, Disk, and Network utilization of SkyhookDM",
 "time": { "from": "2021-06-04T15:01:30.316Z", "to": "2021-06-04T15:26:23.430Z" },
 "templating": {
  "list": [
   { "name": "client", "label": "Client node", "query": "${VAR_CLIENT}" }
  ]
 },
 "panels": [
  {
   "title": "Client CPU Usage (%)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "100 - (avg by (instance) (rate(node_cpu_seconds_total{job=\"node\",mode=\"idle\",instance=\"ms1004.utah.cloudlab.us:9100\"}[1m])) * 100)"
    }
   ]
  },
  {
   "title": "Storage CPU Usage (%)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "100 - (avg by (instance) (rate(node_cpu_seconds_total{job=\"node\",mode=\"idle\",instance!=\"ms1004.utah.cloudlab.us:9100\"}[1m])) * 100)"
    }
   ]
  },
  {
   "title": "Memory Usage (Storage)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes/node_memory_MemTotal_bytes{instance!=\"ms1004.utah.cloudlab.us:9100\"}))*100"
    }
   ]
  },
  {
   "title": "Memory Usage (Client)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes/node_memory_MemTotal_bytes{instance=\"ms1004.utah.cloudlab.us:9100\"}))*100"
    }
   ]
  },
  {
   "title": "Storage Disk I/O",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(node_disk_read_bytes_total{device=\"nvme0n1\",instance!=\"ms1004.utah.cloudlab.us:9100\"}[5m])"
    }
   ]
  },
  {
   "title": "Client Network I/O",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{device=\"eno1d1\",instance=\"ms1004.utah.cloudlab.us:9100\"}[5m])"
    }
   ]
  }
 ]
}